# Generated by Django 5.2.6 on 2025-09-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('Plate_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Car_Model', models.CharField(max_length=120)),
                ('Body_Type', models.CharField(max_length=70)),
                ('Mileage', models.IntegerField()),
                ('Engine_Type', models.CharField(max_length=20)),
                ('Make_Date', models.DateField()),
                ('Fuel_Type', models.CharField(max_length=30)),
                ('Horsepower', models.PositiveIntegerField()),
            ],
        ),
    ]
